create extension if not exists "uuid-ossp";

create table if not exists producto (
    producto_id uuid not null,
    nombre varchar(255) not null,
    categoria varchar(255) not null,
    status varchar(255) not null,
    descripcion varchar(255) not null,
    valor numeric(38,2) not null,
    creado_en timestamp(6) not null,
    actualizado_en timestamp(6),
    primary key (producto_id)
    );

create table if not exists foto (
    foto_id bigint not null generated by default as identity,
    file_name varchar(255) not null,
    link varchar(255) not null,
    producto_id uuid not null,
    creado_en timestamp(6) not null,
    actualizado_en timestamp(6),
    primary key (foto_id),
    foreign key (producto_id) references producto
);

create table if not exists tag (
    producto_id uuid not null,
    tag varchar(255) not null,
    foreign key (producto_id) references producto
);