# Log
logging.level.br.com.alura=DEBUG

# Message
message.market-place.queue-exchange=market-place-queue-exchange
message.market-place.dlq-exchange=market-place-dlq-exchange
message.registro-producto.queue-name=registro-producto-queue
message.registro-producto.dlq-name=registro-producto-dlq
message.registro-producto.routing-key=registro-producto-routing-key